version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: chatbot-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: chatbot
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - chatbot-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/chatbot --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  chatbot-network:
    driver: bridge
